install:
  - npm install
  - bundle install

script: npm run build

deploy:
  provider: heroku
  api_key:
    secure: K6GGJCpw0bWCUzU4hZZOm3a2BQ/Z0P0bbcxixDaWTS8im0+XwiuqNW4StB/pUBQqN5rQU/JuYxcrGneQMeISqfYZow3IRzq6/+Hv4N4saNJAzPJ95L+kC/6g0ybxmuHuhOq8m59zqpveAOsSlhf1WOcGvAxym0GykM61pMN7yR4bZsNbOWIPXDjCI09BFPR/hh7jinU4F3NYyJYXzG9y+brqGd/6wo7HFDYE+M9o0IgM3k63DE1EZ3OD5AObPAz68hIESvry1sQlbAGJEy2eN1H/01Oc8M5g2ARQsoitRgCSwPpbNFIvXz9MOIxhnQZrzX+9PVsp++2edztOEvGwj+A1iZX15fdDBN0m8gJ5PaFR/K2u3/t3WI3DyXPTiYT5eT2tGh28bnfzoYSrm83W4VvCCOGVe99brF0ctxqr76QF53tWWK0QmGeN9Ve4leH5TL4ZnS9FVEvQ6sayoAKCr03oZwCqF/P/kLuei5m9Ei0Xe/SlnGgGHf/1+OADHSsB5jZy11YRtYwpPeJffp/P8gjQxWsQgjCm5CRyd9dEV3rCPAybDAixBl1elWH1nQqq06GLVUUy9VyIVmLU6EEU0vnjClBSXSvgbrYAKbhm0s3sCqpE0oDfuQJY0lFOkm0nPVntjf67KZShjcMwC2Kz2p4ImlzbmqsQV6QeqF3g1Cc=
  app: 
    master: wiki-playlist-staging
    production: wiki-playlist
  on: production
  run: "rake db:migrate"

notifications:
  slack:
    secure: NDdAfCh4+3jZkBMNwH/PSDf7Azjtf0Rv+2OtX/vqg7Fq26gMAtqVpwpMlEXiFC4sKUW6u/JbwXL9BlLvO9p8EfhdI43+Iwq4yP8JzGFOy6l/mUwT3mlnPI9c8yng8VWo/1CahL/sUYVelsmlZyU3n7dFYEmaALQMPdu7Xs4eyhkdwzU02Tu67w8VhDPEXB5pWTNXsuOBNSZD5Ye90uggSE/+PlORcTunUDPMAfPZ4xCl9mOhpBsQ6qXPtDargSlBlcJcrPB8iOMHMZ1pM8LbAW9F2fY7RjeTiiKJpCQGMRLyQ666ZBxu+1tddFkt+plru6dnHnC+hsWJeK2FKuekQGOJhy5/f3R+zBPl3WlXWtNHD8dN56u7ihwbBmiL/ZCL0NvMfCL0tvAtRg21fYpvIB1Zpj8OIkTgtK2W3STyD2g8Lk5R99D+n5eCDqjyegbvE5n3Hxf2NKBrpWO/4MUu4gOTf96FqcApC0k/joWXf3e8bvL6dcGJ3tP3ObulhIatV1FDK0o47lJmqj71BYj2vPpeQfmjSj4klxWHbMFTw0OOtgg5gnD2EyPr69Ax/KQJMZ8YTvKMn2lxe7nEZOdnuf6MBNbWOXLrzvlP+72muAqkBMM/vUM8PRiKDhGraHOQW0uj5vVytybqcMstBC3aRMRnDZXCX7n3c8r07Ccb39Y=
