#!/usr/bin/env bash


if [[ "$1" != "" ]]; then
  MESSAGE="$1"
else
  MESSAGE="Build and Deploy"
fi

npm run build
wait
git add .
eval "git commit -m '$MESSAGE'"
git push origin master
git push wintr master
git push heroku master