#!/usr/bin/env bash


if [[ "$1" != "" ]]; then
  MESSAGE="'$1'"
else
  MESSAGE="Build and Deploy"
fi

npm run build
wait
echo "done with build!"
git add -A
eval git "commit -m $MESSAGE"
echo "done with commit!"
git push origin master
git push wintr master
git push heroku master