#!/usr/bin/env bash

bundle install
npm install
npm run build
git config user.name ${GIT_NAME}
git config user.email ${GIT_EMAIL}
git add .
git commit -m "Deploy assets"
git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" $TRAVIS_BRANCH > /dev/null 2>&1