// Actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_USER = 'ADD_USER';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const ADD_SEARCH = 'ADD_SEARCH';
export const SEARCHING = 'SEARCHING';
export const SET_EDIT_ARTICLE = 'SET_EDIT_ARTICLE';
export const UPDATE_PATH = 'UPDATE_PATH';
export const ADD_ARTICLE_CARD = 'ADD_ARTICLE_CARD';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_IMAGES = 'ADD_ARTICLE_IMAGES';
export const SET_ARTICLE_IMAGE = 'SET_ARTICLE_IMAGE';
export const SET_ARTICLE_CAPTION = 'SET_ARTICLE_CAPTION';
export const EXPAND_ARTICLE = 'EXPAND_ARTICLE';
export const COLLAPSE_ARTICLE = 'COLLAPSE_ARTICLE';
export const COLLAPSE_COMPLETE = 'COLLAPSE_COMPLETE';
export const SET_PLAYLIST_CAPTION = 'SET_PLAYLIST_CAPTION';
export const EDITING_PLAYLIST_CAPTION = 'EDITING_PLAYLIST_CAPTION';
export const EDITING_PLAYLIST_TITLE = 'EDITING_PLAYLIST_TITLE';
export const SET_PLAYLIST_TITLE = 'SET_PLAYLIST_TITLE';
export const RECEIVE_PLAYLIST_PERMALINK = 'RECEIVE_PLAYLIST_PERMALINK';
export const FLASH_MESSAGE = 'FLASH_MESSAGE';
export const HANDLE_DELETE = 'HANDLE_DELETE';
export const RECEIVE_SHARE_INFO = 'RECEIVE_SHARE_INFO';
export const SHARE_IMAGE_RENDERING = 'SHARE_IMAGE_RENDERING';
export const SET_USER_ONBOARDING = 'SET_USER_ONBOARDING';
export const SET_ONBOARDING_STEP = 'SET_ONBOARDING_STEP';
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const CLOSE_LOGIN = 'CLOSE_LOGIN';
export const SHOW_SHARE = 'SHOW_SHARE';
export const CLOSE_SHARE = 'CLOSE_SHARE';

// Breakpoints
export const MD = '756px';

// MISC
export const MINIMUM_ARTICLES = (process.env.NODE_ENV === 'development' ? 1 : 3);


// LIMITS
export const TITLE_LIMIT = 70;
export const CAPTION_LIMIT = 200;

// Sharing
const LOCAL_FACEBOOK_APP_ID = 1022346264473268;
const HEROKU_FACEBOOK_APP_ID = 1645762445689430;
export const FACEBOOK_APP_ID = (process.env.NODE_ENV === 'development' ? LOCAL_FACEBOOK_APP_ID : HEROKU_FACEBOOK_APP_ID);