// Actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_USER = 'ADD_USER';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const FETCH_QUERY = 'FETCH_QUERY';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const ADD_SEARCH = 'ADD_SEARCH';
export const SET_EDIT_ARTICLE = 'SET_EDIT_ARTICLE';
export const UPDATE_PATH = 'UPDATE_PATH';
export const ADD_ARTICLE_CARD = 'ADD_ARTICLE_CARD';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_IMAGES = 'ADD_ARTICLE_IMAGES';
export const SET_ARTICLE_IMAGE = 'SET_ARTICLE_IMAGE';
export const SET_ARTICLE_CAPTION = 'SET_ARTICLE_CAPTION';
export const EXPAND_ARTICLE = 'EXPAND_ARTICLE';
export const COLLAPSE_ARTICLE = 'COLLAPSE_ARTICLE';
export const COLLAPSE_COMPLETE = 'COLLAPSE_COMPLETE';
export const SET_PLAYLIST_CAPTION = 'SET_PLAYLIST_CAPTION';
export const EDITING_PLAYLIST_CAPTION = 'EDITING_PLAYLIST_CAPTION';
export const EDITING_PLAYLIST_TITLE = 'EDITING_PLAYLIST_TITLE';
export const SET_PLAYLIST_TITLE = 'SET_PLAYLIST_TITLE';

// Breakpoints
export const MD = '756px';